<?xml version="1.0" ?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:macro name="create_base" params="wheel_separation wheel_radius wheel_width base_diameter *mesh visualize:=false">

    <xacro:include filename="$(find ca_description)/urdf/create_base_gazebo.xacro"/>
    <xacro:include filename="$(find ca_description)/urdf/create_caster_wheel.xacro"/>
    <xacro:include filename="$(find ca_description)/urdf/create_wheel.xacro"/>
    <xacro:include filename="$(find ca_description)/urdf/sensors/imu_sensor.xacro"/>
    <xacro:include filename="$(find ca_description)/urdf/sensors/wall_sensor.xacro"/>
    <xacro:include filename="$(find ca_description)/urdf/sensors/cliff_sensors.xacro"/>

    <xacro:property name="base_link_offset_z" value="0.0308"/>
    <xacro:property name="base_offset_z" value="0.017"/>
    <xacro:property name="base_height" value="0.0611632"/>
    <xacro:property name="base_mass" value="2"/>

    <link name="base_footprint"/>

    <joint name="base_footprint_joint" type="fixed">
      <origin xyz="0 0 ${base_offset_z}" rpy="0 0 0" />
      <parent link="base_footprint" />
      <child link="base_link" />
    </joint>

    <link name="base_link">
      <xacro:inertial_cylinder mass="${base_mass}" radius="${base_diameter/2}" length="${base_height}"/>

      <visual>
        <origin xyz=" 0 0 ${base_link_offset_z}" rpy="0 0 0" />
        <geometry>
          <xacro:insert_block name="mesh" />
        </geometry>
      </visual>

      <collision>
        <origin xyz="0 0 ${base_link_offset_z}" rpy="0 0 0" />
        <geometry>
          <cylinder length="${base_height}" radius="${base_diameter/2}" />
        </geometry>
      </collision>
    </link>

    <xacro:wall_sensor visualize="${visualize}"/>
    <xacro:cliff_sensors visualize="${visualize}"/>
    <xacro:imu_sensor/>

    <xacro:create_wheel prefix="left" y_offset="${wheel_separation / 2}" wheel_radius="${wheel_radius}" wheel_width="${wheel_width}"/>
    <xacro:create_wheel prefix="right" y_offset="${wheel_separation / -2}" wheel_radius="${wheel_radius}" wheel_width="${wheel_width}"/>
    <xacro:caster_wheel/>

    <!-- Simulation sensors -->
    <xacro:sim_create_base/>
  </xacro:macro>
</robot>
